---
-   hosts: localhost
    vars_files:
        - vars.yml
    gather_facts: false
    sudo: yes

    tasks:
        - name: Pull sources from the repository.
          git: repo={{repo_url}} dest={{project_root}} version=master force=yes
          notify:
            - restart web server

    handlers:
      - include : handlers.yml
