-
    hosts: localhost
    sudo: yes
    connection: local
    gather_facts: no
    vars:
        app_name: PleaseDeploy
        repo_url: 'https://github.com/snehil1001/docker_build'
        repo_remote: origin
        repo_version: master
        webapps_dir: /deployed
        virtualenv_root: /deployed/PleaseDeploy/files
    tasks:
        -
            name: 'git pull project'
            git: 'repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version=master'
            notify: ['restart app']
        -
            name: 'install things'
            pip: name=virtualenv
        -
            name: 'create virtualenv'
            command: 'virtualenv /deployed/PleaseDeploy/venv'
        -
            name: 'activate virtualenv'
            command: '/bin/bash /deployed/PleaseDeploy/venv/bin/activate'
    handlers:
        -
            name: 'restart app'
            supervisorctl: 'name={{app_name}} state=restarted'

